name: Release on Merge

on:
  push:
    branches: [main, canary, develop]

jobs:
  create_release_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Get current date and time
        id: datetime
        run: echo "::set-output name=datetime::$(date -u +'%Y%m%d%H%M%S')"

      - name: Create release tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=${{ steps.branch_name.outputs.branch }}
          DATE_TIME=${{ steps.datetime.outputs.datetime }}
          TAG_NAME="${DATE_TIME}-${BRANCH_NAME}"

          echo "Creating tag ${TAG_NAME}"
          git tag ${TAG_NAME}
          git push origin ${TAG_NAME}
